### ISSUE TITLE
how can i install youbot_driver_ros_interface

### ISSUE THREAD

**Issue by ChefOtter** [youbot/youbot_driver_ros_interface#12]
Hi wnowak,
I am working with ROS, i try to program Kuka youbot. I installed ros-indigo-youbot-driver-ros-interface but it shows me error. Here is the error code:
Errors were encountered while processing:
 ros-indigo-youbot-driver-ros-interface
E: Sub-process /usr/bin/dpkg returned an error code (1)

I am using Ubuntu 14.04 LTS 03 with ROS Indigo. 

You released also new version of youbot_driver_ros_interface. If i try to install it, unfortunately i am getting the same error. How can i install the new release from this driver in ROS Indigo?

i tried to install with this command : sudo apt-get -f install, i am getting following error.

Setting up ros-indigo-youbot-driver-ros-interface (1.1.0-0trusty-20151113-064635-0800) ...
Running setcap for youbot_wrapper...
Failed to set capabilities on file `/opt/ros/hydro/lib/youbot_driver_ros_interface/youbot_driver_ros_interface' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
dpkg: error processing package ros-indigo-youbot-driver-ros-interface (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 ros-indigo-youbot-driver-ros-interface
E: Sub-process /usr/bin/dpkg returned an error code (1)

I tried also following commands
 sudo apt-get install ros-indigo-youbot-driver-ros-interface
 sudo setcap cap_net_raw+ep /opt/ros/indigo/lib/youbot_driver_ros_interface/youbot_driver_ros_interface
 sudo ldconfig /opt/ros/indigo/lib
but nothing changed.

And also i tried following link what you released 
https://github.com/youbot-release/youbot_driver_ros_interface-release/tree/debian/indigo/trusty/youbot_driver_ros_interface
also nothin changed.
My question is, how can i install this driver without problem? Do you have any suggestions?

Thank you for advance 
wish happy new year
Regards

**Comment by wnowak** [comment]
There was an error with the installation script for Indigo. With the next ROS Debian update cycle it should be fixed.
Until that it is still recommended to check out the youbot-driver-ros-interface for Indigo as source code, instead of installing via apt-get.

**Comment by frederikhegger** [comment]
@ChefOtter: does it work for you now?

**Comment by ChefOtter** [comment]
i didn't test yet i will let you know

**Comment by ChefOtter** [comment]
@frederikhegger @wnowak 
I tried the **youbot_driver_ros_interface** library it worked this time without any error.
thanks

**Comment by frederikhegger** [comment]
Okay, thanks.
